<a href="https://colab.research.google.com/github/ErinCrumpBtech/cool-repo/blob/main/Lecture_06_27_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_csv('titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [2]:
import numpy as np

In [3]:
numbers_list = [4,24,100,17,1]

In [4]:
numbers_array = np.array(numbers_list)

In [5]:
print numbers_list

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (<ipython-input-5-bb7451c355f9>, line 1)

In [6]:
print(numbers_list)

[4, 24, 100, 17, 1]


In [8]:
print(numbers_array)

[  4  24 100  17   1]


In [9]:
type(numbers_list)

list

In [11]:
type(numbers_array)

numpy.ndarray

In [12]:
numbers_list * 3

[4, 24, 100, 17, 1, 4, 24, 100, 17, 1, 4, 24, 100, 17, 1]

In [13]:
numbers_array * 3

array([ 12,  72, 300,  51,   3])

In [14]:
print(numbers_array)

[  4  24 100  17   1]


In [15]:
numbers_array.reshape(-1,1)

array([[  4],
       [ 24],
       [100],
       [ 17],
       [  1]])

In [25]:
np.linspace(45,59,4)

array([45.        , 49.66666667, 54.33333333, 59.        ])

In [26]:
np.arange(45,59,.2)

array([45. , 45.2, 45.4, 45.6, 45.8, 46. , 46.2, 46.4, 46.6, 46.8, 47. ,
       47.2, 47.4, 47.6, 47.8, 48. , 48.2, 48.4, 48.6, 48.8, 49. , 49.2,
       49.4, 49.6, 49.8, 50. , 50.2, 50.4, 50.6, 50.8, 51. , 51.2, 51.4,
       51.6, 51.8, 52. , 52.2, 52.4, 52.6, 52.8, 53. , 53.2, 53.4, 53.6,
       53.8, 54. , 54.2, 54.4, 54.6, 54.8, 55. , 55.2, 55.4, 55.6, 55.8,
       56. , 56.2, 56.4, 56.6, 56.8, 57. , 57.2, 57.4, 57.6, 57.8, 58. ,
       58.2, 58.4, 58.6, 58.8])

In [38]:
np.random.random()*100

74.68910615721013

In [39]:
np.argmax(numbers_array)

2

In [40]:
print(numbers_array)

[  4  24 100  17   1]


In [41]:
np.argmin(numbers_array)

4

In [42]:
np.where(numbers_array < 17,'small','big')

array(['small', 'big', 'big', 'big', 'small'], dtype='<U5')

In [43]:
df['AgeGroup'] = np.where(df['Age'] > 54, 'Old',np.where(df['Age'] > 45, 'Middle Age', 'Young'))

In [44]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked AgeGroup  
0      0         A/5 21171   7.2500   NaN        S    Young  
1      0          PC 17599  71.2833   C85        C    Young  
2      0  STON/O2. 3101282   7.9250   NaN        S    Young  
3      0            113803  53.1000  C123        S    Young  
4      0            373450   8.0500   NaN        S    Young

In [45]:
print(df.head(50))

    PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   
20           21         0       2   
21           22         1       2   
22           23         1       3   
23           24         1       1   
24           25         0       3   
25           26         1       3   
2